import "@fortawesome/fontawesome-svg-core/styles.css";
import { LayoutWrapper } from "@/components/LayoutWrapper/LayoutWrapper";
import { config } from "@fortawesome/fontawesome-svg-core";
import "./globals.css";

config.autoAddCss = false;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LayoutWrapper children={children} />
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
