import { Montserrat } from "next/font/google";
import "./globals.css";
import { LayoutWrapper } from "@/components/LayoutWrapper/LayoutWrapper";

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${montserrat.variable}`}>
        <LayoutWrapper children={children} />
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
